services:
  postgres:
    image: postgres:15-alpine
    container_name: local_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: astro
      POSTGRES_PASSWORD: astro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    image: docker.io/valkey/valkey:8-alpine
    container_name: local_valkey
    restart: unless-stopped
    command: valkey-server --save 30 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data

volumes:
  postgres_data:
  valkey-data:
